title: Real time messaging code
description: Draft version
template:
  repo: real-time-messaging-code-template
  name: real-time-messaging-code
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
